import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header";
import localFont from "next/font/local"
import Footer from "./_components/footer";

export const modaniRegular = localFont({
  src: "./fonts/MadaniArabicRegular.ttf",
  weight: "400"
})
export const modaniBold = localFont({
  src: "./fonts/MadaniArabicBold.ttf",
  weight: "700"
})

export const metadata: Metadata = {
  title: "Workshop Aurum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
