import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header";
import localFont from "next/font/local"
import Footer from "./_components/footer";

const modaniRegular = localFont({
  src: "./fonts/MadaniArabicRegular.ttf",
  weight: "400"
})
export const metadata: Metadata = {
  title: "Workshop Aurum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${modaniRegular.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
